package com.esboco_comix.model.enuns;

public enum StatusPedido {
    EM_PROCESSAMENTO,
    REPROVADO,
    APROVADO,
    CANCELADO,
    EM_TRANSPORTE,
    ENTREGUE,
    TROCA_SOLICITADA,
    TROCA_ACEITA,
    TROCA_CONCLUIDA,
    TROCA_RECUSADA,
    DEVOLUCAO_SOLICITADA,
    DEVOLUCAO_RECUSADA,
    DEVOLUCAO_CONCLUIDA;
}
