package com.esboco_comix.pedido.dominio.enuns;

public enum StatusPedido {
    EM_PROCESSAMENTO,
    REPROVADO,
    APROVADO,
    CANCELADO,
    EM_TRANSPORTE,
    ENTREGUE,
    TROCA_SOLICITADA,
    TROCA_ACEITA,
    TROCA_CONCLUIDA,
    TROCA_RECUSADA,
    DEVOLUCAO_SOLICITADA,
    DEVOLUCAO_ACEITA,
    DEVOLUCAO_CONCLUIDA,
    DEVOLUCAO_RECUSADA
}
